//
/// \file plugins/devopoly/propertytypes.h
/// \brief Property types
//

#ifndef PLUGINS_DEVOPOLY_PROPERTYTYPES_H
#define PLUGINS_DEVOPOLY_PROPERTYTYPES_H

enum DevopolyPropertyType
{
	DEVOPOLY_PROPERTY_TYPE_PURPLE,
	DEVOPOLY_PROPERTY_TYPE_CYAN,
	DEVOPOLY_PROPERTY_TYPE_BROWN,
	DEVOPOLY_PROPERTY_TYPE_ORANGE,
	DEVOPOLY_PROPERTY_TYPE_RED,
	DEVOPOLY_PROPERTY_TYPE_YELLOW,
	DEVOPOLY_PROPERTY_TYPE_GREEN,
	DEVOPOLY_PROPERTY_TYPE_BLUE,
	DEVOPOLY_PROPERTY_TYPE_RAILROAD,
	DEVOPOLY_PROPERTY_TYPE_UTILITY,
};

#endif // PLUGINS_DEVOPOLY_PROPERTYTYPES_H

